packageNum: 636
packageIdent: knb-lter-cap.636.7
title: "CAP LTER weather stations at Papago Park and Lost Dutchman State Park in the greater Phoenix metropolitan area, ongoing since 2010"
geographicCoverage:
  geographicDescription: 'CAP LTER study area: greater Phoenix, Arizona (USA)
  metropolitan area and surrounding Sonoran desert region'
