packageNum: 636
packageIdent: knb-lter-cap.636.10
baseURL: https://data.gios.asu.edu/datasets/cap/
project: lter
title: "CAP LTER weather stations at Papago Park and Lost Dutchman State Park in the greater Phoenix metropolitan area, ongoing since 2010"
maintenance: regular
geographicCoverage:
  geographicDescription: 'CAP LTER study area: greater Phoenix, Arizona (USA)
  metropolitan area and surrounding Sonoran desert region'
