---
title: "knb-lter-cap.636"
author: "CAP LTER Information Manager"
---

## micromet_data

```{r}
#| label: micromet-data
#| echo: FALSE
#| eval: TRUE
#| warning: TRUE

micromet_data <- DBI::dbGetQuery(
  pg, "
  SELECT
    events.timestamp,
    sites.site_code,
    events.replicate,
    variables.variablecode,
    observations.reading
  FROM micromet.events
  JOIN micromet.observations ON (observations.event_id = events.id)
  JOIN micromet.variables ON (variables.id = observations.variable_id)
  JOIN micromet.sites ON (sites.id = events.site_id)
  -- WHERE
  --   timestamp >= '2021-01-01'
  ORDER BY
    sites.site_code,
    events.timestamp,
    events.replicate,
    variables.variablecode
  ;
  "
)

micromet_data <- micromet_data |>
  tidyr::pivot_wider(
    names_from  = variablecode,
    values_from = reading
  ) |>
  dplyr::mutate(
    site_code = as.factor(site_code)
  )

names(micromet_data) <- tolower(names(micromet_data))

expected_names <- c(
  "timestamp",
  "site_code",
  "replicate",
  "airtc_avg",
  "rh",
  "slrkw_avg",
  "slrmj_tot",
  "ws_ms_avg",
  "winddir",
  "rain_mm_tot"
)

```

## DT: micromet_data_2021_present

```{r}
#| label: micromet-data-2021-present
#| echo: FALSE
#| eval: TRUE
#| warning: TRUE

micromet_data_2021_present <- micromet_data |>
  dplyr::filter(timestamp >= "2021-01-01") |>
  pointblank::col_exists(
    columns = expected_names,
    actions = pointblank::stop_on_fail()
  )

try({
  capeml::write_attributes(micromet_data_2021_present, overwrite = FALSE)
  capeml::write_factors(micromet_data_2021_present, overwrite = FALSE)
})

# capeml::update_attributes(micromet_data_2021_present)

```


## DT: micromet_data_2011_2020

```{r}
#| label: micromet-data-2011-2020
#| echo: FALSE
#| eval: TRUE
#| warning: TRUE

micromet_data_2011_2020 <- micromet_data |>
  dplyr::filter(timestamp >= "2011-01-01" & timestamp <= "2020-12-31") |>
  pointblank::col_exists(
    columns = expected_names,
    actions = pointblank::stop_on_fail()
  )

# try({
#   capeml::write_attributes(micromet_data_2011_2020, overwrite = FALSE)
#   capeml::write_factors(micromet_data_2011_2020, overwrite = FALSE)
# })

# micromet_data_2011_2020_DT <- capeml::harvest_dataTable("data_2011_2020/micromet_data_2011_2020_DT.xml")

```


## DT: micromet_data_2006_2010

```{r}
#| label: micromet-data-2006-2010
#| echo: FALSE
#| eval: TRUE
#| warning: TRUE

micromet_data_2006_2010 <- micromet_data |>
  dplyr::filter(timestamp <= "2010-12-31") |>
  pointblank::col_exists(
    columns = expected_names,
    actions = pointblank::stop_on_fail()
  )

# try({
#   capeml::write_attributes(micromet_data_2006_2010, overwrite = FALSE)
#   capeml::write_factors(micromet_data_2006_2010, overwrite = FALSE)
# })

# capeml::update_attributes(micromet_data_2006_2010)

# micromet_data_2006_2010_DT <- capeml::harvest_dataTable("data_2006_2010/micromet_data_2006_2010_DT.xml")

```


## OE: micromet_programs (DBG and LDP)

see `data_objects.yaml`


## DT: maintenance_log

```{r}
#| label: maintenance-log
#| eval: TRUE
#| error: TRUE

maintenance_log <- readr::read_csv("maintenance_log.csv") |>
  dplyr::rename(site_code = site) |>
  dplyr::mutate(site_code = as.factor(site_code))

# try({
#   capeml::write_attributes(maintenance_log, overwrite = FALSE)
#   capeml::write_factors(maintenance_log, overwrite = FALSE)
# })

```


## coverages

```{r}
#| label: coverages
#| eval: TRUE
#| error: TRUE

# LDP geographic

ldp_coords <- EML::eml$boundingCoordinates(
  westBoundingCoordinate  = "-111.4795",
  eastBoundingCoordinate  = "-111.4789",
  northBoundingCoordinate = "33.4626",
  southBoundingCoordinate = "33.4622"
)

ldp_geo <- EML::eml$geographicCoverage(
  geographicDescription = "CAP LTER site at Lost Dutchman State Park, AZ, USA",
  boundingCoordinates   = ldp_coords,
  id                    = "geographicCoverage.LDP"
)

# DGB geographic

dbg_coords <- EML::eml$boundingCoordinates(
  westBoundingCoordinate  = "-111.9476",
  eastBoundingCoordinate  = "-111.9415",
  northBoundingCoordinate = "33.4612",
  southBoundingCoordinate = "33.4554"
)

# geographic

dbg_geo <- EML::eml$geographicCoverage(
  geographicDescription = "CAP LTER site at the Desert Botanical Garden, AZ, USA",
  boundingCoordinates   = dbg_coords,
  id                    = "geographicCoverage.DBG"
)

# temporal

end_date <- as.character(as.Date(max(micromet_data$timestamp)))

tower_begin <- EML::eml$beginDate(calendarDate = "2006-05-10")
tower_end   <- EML::eml$endDate(calendarDate = end_date)

tower_range <- EML::eml$rangeOfDates(
  beginDate = tower_begin,
  endDate   = tower_end
)
tower_temporal <- EML::eml$temporalCoverage(rangeOfDates = tower_range)

# coverage
coverage <- EML::eml$coverage(
  geographicCoverage = list(
    ldp_geo,
    dbg_geo
    ),
  temporalCoverage = tower_temporal
)

```


## build

```{r}
#| label: construct-dataset
#| eval: TRUE
#| error: TRUE

dataset <- capeml::create_dataset()
eml     <- capeml::create_eml()

EML::eml_validate(eml)
capeml::write_cap_eml()

# file.remove(c(list.files(pattern = "^636.+csv$")))

```
